# Copyright (c) K-Society and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.
#

branches:
  only:
    - master
    - develop

image: Visual Studio 2019

version: 0.0.0.{build}
platform: Any CPU
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  ComSystemVersion: 0.0.0.0

build:
  verbosity: minimal #quiet|minimal|normal|detailed

build_script:
  - appveyor.cmd
  
after_build:
  - ps: $comSystemPath = Resolve-Path .\Src\00\KSociety.Com.Install\K-Society.Com.exe; $array = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("$comSystemPath").FileVersion -split "\."; $env:ComSystemVersion = $array[0] + "." + $array[1] + "." + $array[2]; Write-Host "$env:ComSystemVersion"

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true
skip_tags: true

#build:
#  publish_nuget: true

artifacts:
  - path: build\**\Release\*.nupkg
    name: nuget
  - path: Src\00\KSociety.Com.Install\ComSystem.exe
    name: comsysteminstaller

deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/k-society/api/v2/package
    api_key:
      secure: jIQOXURv/wJ2bys5OTJpp+zTyN8tyVAnczeodJUK3Nw=
    skip_symbols: true
    symbol_server: 
    artifact: /.*\.nupkg/
    on:
      branch: /^(master|develop)$/
      
  - provider: NuGet
    server: 
    api_key:
      secure: LkTQAh9Tv+IgjhWD5LBCRs7Jc9y5eDKDo+TdnwjuBXVdfuin8jpb1ewtMb30pMxz
    skip_symbols: true
    symbol_server: 
    artifact: /.*\.nupkg/
    on:
      branch: master
         
  - provider: GitHub
    release: ComSystem $(ComSystemVersion)
    description: 'ComSystem $(ComSystemVersion)'
    auth_token:
      secure: 7XvMBiUsnXWGCogi909uIzQVH/68TW4lAipl0RN+ZAwHrlqZChxEBroMRWEcrWGM
    artifact: comsysteminstaller
    draft: false
    prerelease: false
    force_update: true
    tag: $(ComSystemVersion)
    on:
      branch: master
      #appveyor_repo_tag: true