CREATE VIEW [kb].[AllTagGroupAllConnectionView]
	AS SELECT 
	[kb].[AllTagGroupConnectionView].[Id],
	[TagName],
	[kb].[AllConnectionView].[Id] AS [ConnectionId],
	[kb].[AllTagGroupConnectionView].[ConnectionName],
	[kb].[AllTagGroupConnectionView].[AutomationTypeId],
	[kb].[AllTagGroupConnectionView].[AutomationName],
	[kb].[AllTagGroupConnectionView].[Ip],
	[kb].[AllTagGroupConnectionView].[WriteEnable],
	[InputOutput], 
	[AnalogDigitalSignal],
	[MemoryAddress],
	[Invoke],
	[TagGroupId],
	[TagGroupName],
	[Clock],
	[Update],
	[DataBlock],	
	[Offset],
	[BitOfByte],
	[WordLenId],
	[WordLenName],
	[AreaId],
	[AreaName],
	[StringLength],
	--Connection
	[kb].[AllConnectionView].[ConnectionTypeId],
	[kb].[AllConnectionView].[ConnectionTypeName],
	[kb].[AllConnectionView].[CpuTypeId],
	[kb].[AllConnectionView].[CpuTypeName],
	[kb].[AllConnectionView].[Rack],
	[kb].[AllConnectionView].[Slot],
	[kb].[AllConnectionView].[Path]
	FROM [kb].[AllTagGroupConnectionView]
	INNER JOIN [kb].[AllConnectionView] ON [kb].[AllConnectionView].[Id] = [kb].[AllTagGroupConnectionView].[ConnectionId]	
