CREATE VIEW [ksociety].[AllTagGroupAllConnectionView]
	AS SELECT 
	[ksociety].[AllTagGroupConnectionView].[Id],
	[TagName],
	[ksociety].[AllConnectionView].[Id] AS [ConnectionId],
	[ksociety].[AllTagGroupConnectionView].[ConnectionName],
	[ksociety].[AllTagGroupConnectionView].[AutomationTypeId],
	[ksociety].[AllTagGroupConnectionView].[AutomationName],
	[ksociety].[AllTagGroupConnectionView].[Ip],
	[ksociety].[AllTagGroupConnectionView].[WriteEnable],
	[InputOutput], 
	[AnalogDigitalSignal],
	[MemoryAddress],
	[Invoke],
	[TagGroupId],
	[TagGroupName],
	[Clock],
	[Update],
	[DataBlock],	
	[Offset],
	[BitOfByte],
	[WordLenId],
	[WordLenName],
	[AreaId],
	[AreaName],
	[StringLength],
	--Connection
	[ksociety].[AllConnectionView].[ConnectionTypeId],
	[ksociety].[AllConnectionView].[ConnectionTypeName],
	[ksociety].[AllConnectionView].[CpuTypeId],
	[ksociety].[AllConnectionView].[CpuTypeName],
	[ksociety].[AllConnectionView].[Rack],
	[ksociety].[AllConnectionView].[Slot],
	[ksociety].[AllConnectionView].[Path]
	FROM [ksociety].[AllTagGroupConnectionView]
	INNER JOIN [ksociety].[AllConnectionView] ON [ksociety].[AllConnectionView].[Id] = [ksociety].[AllTagGroupConnectionView].[ConnectionId]	
